fail_fast: true
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
      -   id: trailing-whitespace
      -   id: check-yaml
      -   id: debug-statements
      -   id: name-tests-test

  -   repo: https://github.com/asottile/setup-cfg-fmt
      rev: v2.2.0
      hooks:
      -   id: setup-cfg-fmt

  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v3.9.0
      hooks:
      -   id: reorder-python-imports
          exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
          args: [--py38-plus]

  -   repo: https://github.com/asottile/add-trailing-comma
      rev: v2.4.0
      hooks:
      -   id: add-trailing-comma
          args: [--py36-plus]

  -   repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
        - id: black
          args:
            - --line-length 99

  -   repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: 'v0.0.263'
      hooks:
        - id: ruff